/**
 * Copyright 2021 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.10 at 03:10:54 PM IST 
//


package com.automatics.providers.issuemanagement.objects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tel.jaws.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tel.jaws.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jaws.JiraDetails }
     * 
     */
    public Jaws.JiraDetails createJawsJiraDetails() {
        return new Jaws.JiraDetails();
    }

    /**
     * Create an instance of {@link Jaws.Issues }
     * 
     */
    public Jaws.Issues createJawsIssues() {
        return new Jaws.Issues();
    }

    /**
     * Create an instance of {@link Jaws.Issues.IssueDetails.LabelsList }
     * 
     */
    public Jaws.Issues.IssueDetails.LabelsList createJawsIssuesIssueDetailsLabelsList() {
        return new Jaws.Issues.IssueDetails.LabelsList();
    }

    /**
     * Create an instance of {@link Jaws.Issues.IssueDetails.WatcherList }
     * 
     */
    public Jaws.Issues.IssueDetails.WatcherList createJawsIssuesIssueDetailsWatcherList() {
        return new Jaws.Issues.IssueDetails.WatcherList();
    }

    /**
     * Create an instance of {@link Jaws.Issues.IssueDetails }
     * 
     */
    public Jaws.Issues.IssueDetails createJawsIssuesIssueDetails() {
        return new Jaws.Issues.IssueDetails();
    }

    /**
     * Create an instance of {@link Jaws }
     * 
     */
    public Jaws createJaws() {
        return new Jaws();
    }

}
